#!/bin/bash

check-for-branch () {
    if git rev-parse --git-dir >/dev/null 2> /dev/null; then
        PROJ=$(basename `pwd`)
        CURR_BRANCH=`git rev-parse --abbrev-ref HEAD`
        if [ "$1" == "" ]; then
            printf "%-35s" "$PROJ: "
            if [[ -n $(git status -s) ]]; then
                echo -n "* "
            else
                echo -n "  "
            fi
            echo " $CURR_BRANCH"
        else
            if git show-ref --verify --quiet "refs/heads/$1"; then
                printf "%-25s" "$PROJ: "
                if [[ -n $(git status -s) ]]; then
                    echo -n "* "
                else
                    echo -n "  "
                fi
                echo -n $1

                if [ "$CURR_BRANCH" = "$1" ]; then
                    echo -n " (checked out)"
                else
                    echo -n "              "
                fi
                echo
            fi
        fi
    fi

}

export -f check-for-branch

for-each-folder -q check-for-branch $1
