#!/bin/bash -e

failed=()
succeeded=()

quiet=false

while getopts ":qsh" option; do
  case $option in
    q) quiet=true ;;
    h) echo "Usage: $0 [-q] [-s] command..." ;;
    ?) echo "error: no such option -$OPTARG"; exit ;;
  esac
done

# remove the options from the positional parameters
shift $(( OPTIND - 1 ))

for folder in *; do
    if [ ! -d "$folder" ]; then
        continue
    fi
    if [ "$folder" = "." ]; then
        continue
    fi
    if [ "$folder" = ".." ]; then
        continue
    fi
    if [ -d "$folder" ]; then
        ! $quiet && echo
        ! $quiet && echo "$folder:"
        pushd "$folder" >/dev/null
            ret=0
            "$@" || ret=$?
            if [ $ret -ne 0 ]; then
                failed+=("$folder")
            else
                succeeded+=("$folder")
            fi
        popd >/dev/null
    fi
done

if [ ! "$quiet" = true ]; then
    echo
    if [ -n "$succeeded" ]; then
        echo "succeeded: ${succeeded[@]}"
    fi
    echo
    if [ -n "$failed" ]; then
        echo "failed: ${failed[@]}"
    fi
fi
