#!/bin/bash

quiet=false

while getopts ":q" option; do
  case $option in
    q) quiet=true ;;
    ?) echo "error: no such option -$OPTARG"; exit ;;
  esac
done

# remove the options from the positional parameters
shift $(( OPTIND - 1 ))

for f in *; do
    if [ -d "$f" ]; then
        ! $quiet && echo
        ! $quiet && echo "$f:"
        pushd "$f" >/dev/null
        "$@"
        popd >/dev/null
    fi
done
