#!/bin/bash -e

failed=()
succeeded=()

quiet=false

all_folders=true

PARAMS=()
FOLDERS=()

if [ -z "$1" ]; then
    set -- "-h"
fi

while (( "$#" )); do
    case "$1" in
        -q|--quiet)
            quiet=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [-q] [-s] [-f folders...] [--] command..."
            exit 0
            ;;
        -f|--folders)
            all_folders=false
            shift
            # We want to use up params until --.
            # TODO if the user specifies -f without --, give a sensible error
            while [[ "$1" != "--" ]]; do
                FOLDERS+=("$1")
                shift
            done
            shift
            PARAMS=("$@")
            break
            ;;
        --)
            shift
            PARAMS=("$@")
            break
            ;;
        -*|--*)
            echo "error: no such option $1" >&2;
            exit 1
            ;;
        *)
            PARAMS+=("$1")
            shift
            ;;
    esac
done

# remove the options from the positional parameters
set -- "${PARAMS[@]}"

$all_folders && FOLDERS=(*)

for folder in "${FOLDERS[@]}"; do
    echo "folder $folder"
    if [ ! -d "$folder" ]; then
        continue
    fi
    if [ "$folder" = "." ]; then
        continue
    fi
    if [ "$folder" = ".." ]; then
        continue
    fi
    if [ -d "$folder" ]; then
        ! $quiet && echo
        ! $quiet && echo "$folder:"
        pushd "$folder" >/dev/null
            ret=0
            "$@" || ret=$?
            if [ $ret -ne 0 ]; then
                failed+=("$folder")
            else
                succeeded+=("$folder")
            fi
        popd >/dev/null
    fi
done

if [ ! "$quiet" = true ]; then
    echo
    if [ -n "$succeeded" ]; then
        echo "succeeded: ${succeeded[@]}"
    fi
    echo
    if [ -n "$failed" ]; then
        echo "failed: ${failed[@]}"
    fi
fi
