services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MEMORY: 8G
      TYPE: FABRIC
      FABRIC_LAUNCHER_VERSION: 1.1.1
      FABRIC_LOADER_VERSION: 0.19.3
      VERSION: 26.1.2
      UID: "${MINECRAFT_UID:?missing MINECRAFT_UID}"
      GID: "${MINECRAFT_GID:?missing MINECRAFT_GID}"
      SEED: 6378
      WHITELIST: |
        sargon2
      OPS: |
        sargon2
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        ferrite-core
        view-distance-fix:fabric-1.0.2+26.1.2
        geyser:2.10.0-b1162
        floodgate
        viafabric:0.4.21+164-26.x
      VIEW_DISTANCE: 16
      USE_MEOWICE_FLAGS: true
      MOTD: |
        §cFirelight Systems§r §aMINECRAFT§r
        §7Unwind and enjoy!§r
      DIFFICULTY: hard
      ICON: https://www.firelightsystems.com/logo/logo_512x512.png
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "19132:19132/tcp"
      - "19132:19132/udp"
      - "19133:19133/tcp"
      - "19133:19133/udp"
    volumes:
      - ./minecraft_data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
